apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - name: tech-challenge
        image: songwind1/tech-challenge-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "700m"
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
spec:
  type: NodePort
  selector:
    app: tech-challenge
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60


